// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WindTurbineApi.Data;

#nullable disable

namespace WindTurbineApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260223124821_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WindTurbineApi.Models.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AcknowledgedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TurbineId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TurbineId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("WindTurbineApi.Models.OperatorCommand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IssuedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TurbineId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TurbineId");

                    b.ToTable("OperatorCommands");
                });

            modelBuilder.Entity("WindTurbineApi.Models.Turbine", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Turbines");
                });

            modelBuilder.Entity("WindTurbineApi.Models.TurbineMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AmbientTemperature")
                        .HasColumnType("double precision");

                    b.Property<double>("BladePitch")
                        .HasColumnType("double precision");

                    b.Property<double>("GearboxTemp")
                        .HasColumnType("double precision");

                    b.Property<double>("GeneratorTemp")
                        .HasColumnType("double precision");

                    b.Property<double>("NacelleDirection")
                        .HasColumnType("double precision");

                    b.Property<double>("PowerOutput")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("RotorSpeed")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TurbineId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Vibration")
                        .HasColumnType("double precision");

                    b.Property<double>("WindDirection")
                        .HasColumnType("double precision");

                    b.Property<double>("WindSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("TurbineId");

                    b.ToTable("TurbineMetrics");
                });

            modelBuilder.Entity("WindTurbineApi.Models.Alert", b =>
                {
                    b.HasOne("WindTurbineApi.Models.Turbine", "Turbine")
                        .WithMany("Alerts")
                        .HasForeignKey("TurbineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turbine");
                });

            modelBuilder.Entity("WindTurbineApi.Models.OperatorCommand", b =>
                {
                    b.HasOne("WindTurbineApi.Models.Turbine", "Turbine")
                        .WithMany("Commands")
                        .HasForeignKey("TurbineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turbine");
                });

            modelBuilder.Entity("WindTurbineApi.Models.TurbineMetric", b =>
                {
                    b.HasOne("WindTurbineApi.Models.Turbine", "Turbine")
                        .WithMany("Metrics")
                        .HasForeignKey("TurbineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turbine");
                });

            modelBuilder.Entity("WindTurbineApi.Models.Turbine", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Commands");

                    b.Navigation("Metrics");
                });
#pragma warning restore 612, 618
        }
    }
}
